apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pxah
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-pxah@sha256:090f8e63eafb9135a391fdf4dd3268043bb3f04d6b2a5d73d802d957b182611d
        name: my-nodejs
        resources: {}
status: {}
